lib/tasksmanager_web/router.ex
defmodule TasksmanagerWeb.Router do
  use TasksmanagerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasksmanager.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end


  scope "/", TasksmanagerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tasks", TaskController
    get "/feed", PageController, :feed
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete

  end

  # Other scopes may use custom stacks.
   scope "/api/v1", TasksmanagerWeb do
    pipe_through :api
    resources "/timeblocks", TimeBlockController, except: [:new]
   end
end

lib/tasksmanager_web/templates/page/feed.html.eex
<%= if @current_user do %>
  <div class="row">
    <div class="col">
      <%= render TasksmanagerWeb.TaskView, "index.html",
          Map.put(assigns, :action, task_path(@conn, :create)) %>
    </div>
  </div>
<% end %>
<hr />
</div>

lib/tasksmanager_web/templates/page/index.html.eex
<h1>Log In to Task Tracker</h1>
<div class="tag_line"><i><b>....For tracking your tasks easily</b></i></div>
<hr />
   <!-- session_path(@conn, :create) -->
   <%= form_tag("/session", method: :post) do %>

     <div class="form-group">
       Enter your Email:
       <br/>
       <input type="email"  name="email" placeholder="user@example.com" class= "form-control" required>
     </div>
     <br/>
     <!-- passwords come later -->
     <div class="form-group">
       <button class="btn btn-primary">Log in</button>
       <br/>
       <br/>
       New user ? <%= link "Register here", to: user_path(@conn, :new) %>
       <br/>
     </div>
   <% end %>